url: https://kraftychocolates.github.io
baseurl: /

# Site settings
title: "KraftyChocolates - Handcrafted, Delicious Chocolates nor in India:
email: orders@kraftychocolates.in
description: "Premium handcrafted chocolates with rich cocoa taste and exotic flavour options available. We deliver your chocolates at your doorstep. Indulge Yourself!"


# Team names, titles and social links
people:
- name: Pradyumna Chatterjee
  pic: 1
  position: Chocolateer & Geek
  social:
    - title: facebook
      url: https://www.facebook.com/pradyumnacster
    - title: instagram
      url: https://www.instagram.com/pradyumnacster

- name: Souvik Ghosh
  pic: 2
  position: Lead Operations Manager & In-House Blogger
  social:
    - title: facebook
      url: https://www.facebook.com/pradyumnacster
    - title: instagram
      url: https://www.instagram.com/pradyumnacster

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/kraftychoco
  - title: facebook
    url: https://www.facebook.com/kraftychocolates
  - title: instagram
    url:  https://www.instagram.com/kraftychocolates

# Postal address (add as many lines as necessary)
address:
  - line: Baishnavghata-Patuli
  - line: Kolkata, West Bengal, India
  
# Build settings
markdown: kramdown
permalink: pretty
